workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 90
    environment:
      node: 20.0.0
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Build web assets
        script: |
          npx ionic build
      - name: Copy and sync iOS
        script: |
          npx cap copy ios
          npx cap sync ios
      - name: Build iOS app (archive)
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath $CM_BUILD_DIR/build/App.xcarchive
publishing:
  app_store_connect:
    auth: integration
    api_key_path: ChiaveCodemagic
    issuer_id: <35c6e464-0d94-481d-8d44-2c9849bbca91>
    key_id: <77VVA2T5ML>
    bundle_id: "com.daniele.sivapp"
    submit_to_testflight: true
