workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.daniele.sivapp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Build web assets
        script: |
          npx ionic build
      - name: Copy web assets to iOS
        script: |
          npx cap copy ios
      - name: Build iOS app
        script: |
          npx cap sync ios
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive
    artifacts:
      - build/App.xcarchive
    publishing:
      app_store_connect:
        api_key: 
    code_signing:
      ios:
        automatic: true  
