workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 90
    environment:
      node: 20.0.0
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Clean previous web build
        script: rm -rf www
      - name: Build web assets
        script: npx ionic build
      - name: Copy web assets to iOS
        script: npx cap copy ios
      - name: Sync iOS platform
        script: npx cap sync ios
      - name: Build iOS app with Xcode
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
           -scheme App \
           -sdk iphoneos \
           -configuration Release \
           archive \
           -archivePath $CM_BUILD_DIR/build/App.xcarchive \
           CODE_SIGN_STYLE=Automatic \
           -allowProvisioningUpdates

    artifacts:
      - build/App.xcarchive

    publishing:
      app_store_connect:
        api_key_id: "677URXPXN9"
        issuer_id: "35c6e464-0d94-481d-8d44-2c9849bbca91"
        key_file: "AuthKey_U3NC646QJP.p8"
        bundle_id: "com.daniele.sivapp"
        submit_to_testflight: true

    code_signing:
      ios:
        distribution_certificate:
          file: "ios_distribution.p12"
          password: "Dgra75"
          reference_name: "Daniele Doppiu"
        automatic_code_signing: true
