workflows:
  ios-testflight:
    name: iOS TestFlight build
    environment:
      xcode: latest
      node: 20.10.0
      npm: default
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS release
        script: |
          npx cap sync ios
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/ios/App.xcarchive archive
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ios_output
    artifacts:
      - ios_output/*.ipa
    publishing:
      app_store_connect:
        api_key: SivappCodemagic     
        key_id: 677URXPXN9
        issuer_id: 35c6e464-0d94-481d-8d44-2c9849bbca91
        bundle_id: "com.daniele.sivapp"
        submit_to_testflight: true
