workflows:
  ios-ionic-build:
    name: iOS Ionic Build
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "▶️ Installazione Ionic CLI e dipendenze..."
          npm install -g @ionic/cli
          npm ci

      - name: Build Ionic project
        script: |
          echo "▶️ Compilo l'app Ionic..."
          ionic build --prod --verbose || { echo "❌ ionic build fallita"; exit 1; }

          echo "▶️ Controllo contenuto della cartella www/"
          if [ -d www ]; then
            ls -R www
          else
            echo "❌ www/ non esiste dopo build!"
            exit 1
          fi

      - name: Sync Capacitor iOS
        script: |
          echo "▶️ Sincronizzo Capacitor con iOS..."
          npx cap sync ios || { echo "❌ Capacitor sync fallita"; exit 1; }

      - name: Build iOS app (Xcode)
        script: |
          echo "▶️ Compilo l'app iOS (simulatore / debug)..."
          xcodebuild -workspace ios/App/App.xcworkspace \
          -scheme App \
          -sdk iphonesimulator \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
