workflows:
  ionic-ios:
    environment:
      node: v18.17.0
      npm: 9.6.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build Ionic app
        script: |
          # Usa ionic build che dovrebbe chiamare ng build internamente
          npx ionic build --prod
      - name: iOS setup
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          # I tuoi script per il build iOS...
