workflows:
  ios-ionic-build:
    name: iOS Ionic Build
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "▶️ Installo Ionic CLI e dipendenze..."
          npm install -g @ionic/cli
          npm ci
      - name: Build Ionic project
        script: |
          echo "▶️ Compilo l'app Ionic..."
          ionic build --prod || { echo "❌ ionic build fallita"; exit 1; }

          echo "▶️ Trovo la cartella creata da Ionic in dist/..."
          DIST_DIR=$(find dist -mindepth 1 -maxdepth 1 -type d | head -n 1)
          echo "➡️ DIST_DIR trovato: $DIST_DIR"

          echo "▶️ Copio output in www/..."
          rm -rf www
          mkdir www
          cp -R "$DIST_DIR"/* www/ || { echo "❌ Copia fallita"; exit 1; }

          echo "▶️ Contenuto di www/:"
          ls -R www
      - name: Sync Capacitor iOS
        script: |
          echo "▶️ Sincronizzo Capacitor con iOS..."
          npx cap sync ios
      - name: Build iOS app (Xcode)
        script: |
          echo "▶️ Compilo con Xcode (senza firma)..."
          xcodebuild -workspace ios/App/App.xcworkspace \
          -scheme App \
          -sdk iphonesimulator \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa
