workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_ID: "com.daniele.sivapp"  
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Build web assets
        script: |
          npx ionic build
      - name: Copy web assets to iOS
        script: |
          npx cap copy ios
      - name: Build iOS app
        script: |
          npx cap sync ios
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath $CM_BUILD_DIR/build/App.xcarchive
    artifacts:
      - build/App.xcarchive
    code_signing:
      ios:
        distribution_certificate:
          p12_path: ios/ios_distribution.p12
          p12_password: "Dgra75"  
        provisioning_profile_path: ios/App_Store_Profile.mobileprovision
        automatic: false
