workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: latest
      npm: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: SivappCodemagic
        APP_STORE_CONNECT_ISSUER_ID: 35c6e464-0d94-481d-8d44-2c9849bbca91
        APP_STORE_CONNECT_PRIVATE_KEY: 677URXPXN9
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @ionic/cli
          npm ci
      - name: Build iOS release
        script: |
          ionic capacitor build ios --prod --release
      - name: Archive app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=$APP_STORE_TEAM_ID \
            PROVISIONING_PROFILE_SPECIFIER=""
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ios/App \
            -exportOptionsPlist $CM_BUILD_DIR/ExportOptions.plist
    artifacts:
      - ios/App/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
