workflows:
  ionic-ios:
    name: Ionic iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tuodominio.tuaapp # CAMBIA QUESTO
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: v18.19.0
      npm: 10.2.0
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build Ionic app
        script: |
          echo "🔍 Building with Angular CLI directly..."
          npx ng build --configuration=production --verbose
          
          echo "🔍 Checking build output structure..."
          ls -la
          
          if [ -d "www" ]; then
            echo "✅ www directory exists"
            ls -la www/
          else
            echo "❌ www directory not found"
          fi
          
          # Check if files are in a subdirectory
          find . -name "index.html" -type f 2>/dev/null || echo "No index.html found anywhere"
          
          # If index.html is in www/browser/, move it up
          if [ -f "www/browser/index.html" ]; then
            echo "🔧 Moving files from www/browser/ to www/"
            mv www/browser/* www/ 2>/dev/null || true
            rmdir www/browser 2>/dev/null || true
          fi
          
          # Final check
          if [ ! -f "www/index.html" ]; then
            echo "❌ Still no index.html in www/"
            echo "Trying ionic build as fallback..."
            npx ionic build --prod --verbose
          fi
      - name: Verify build output
        script: |
          if [ ! -f "www/index.html" ]; then
            echo "❌ Build failed - no index.html found"
            echo "Directory structure:"
            find . -maxdepth 3 -type f -name "*.html" 2>/dev/null || echo "No HTML files found"
            exit 1
          else
            echo "✅ Build successful - index.html found"
            ls -la www/
          fi
      - name: Capacitor sync
        script: |
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # Uncomment the following section to publish to App Store Connect
      # app_store_connect:
      #   auth: integration
      #   
      #   # Configuration related to TestFlight (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_testflight: true
      #   beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
      #     - group name 1
      #     - group name 2
      #
      #   # Configuration related to App Store (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_app_store: false
      
      email:
        recipients:
          - tuaemail@example.com # CAMBIA QUESTO
        notify:
          success: true
          failure: true
