workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        NODE_VERSION: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "▶️ Installo dipendenze NPM..."
          cd $CM_BUILD_DIR
          npm ci
      - name: Ionic Build
        script: |
          echo "▶️ Directory corrente:"
          pwd
          echo "📂 Contenuto directory corrente:"
          ls -la

          echo "▶️ Avvio build Ionic..."
          npx ionic build --prod --verbose || { echo "❌ ionic build fallita"; exit 1; }

          echo "▶️ Controllo contenuto cartella www/"
          if [ -f www/index.html ]; then
            echo "✅ index.html trovato!"
            ls -R www
          else
            echo "❌ index.html mancante!"
            ls -R
            exit 1
          fi
      - name: Sync Capacitor
        script: |
          echo "▶️ Capacitor sync iOS..."
          npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
