workflows:
  ionic-ios:
    name: Ionic iOS Build
    environment:
      node: v18.17.0
      npm: 9.6.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Ionic app
        script: npx ionic build --prod
      - name: Capacitor sync
        script: npx cap sync ios
      - name: Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa --workspace ios/App/App.xcworkspace --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # Le tue configurazioni per App Store
